import { and, eq, gte, lte, sql, sum } from "drizzle-orm";
import { getDb, isDatabaseConfigured } from "@/db/client";
import { orders, payments, refunds } from "@/db/schema";
import { getRazorpay } from "@/lib/razorpay";
import { isRazorpayConfigured } from "@/lib/env";
import { logger } from "@/lib/logger";
import { createHash, randomUUID } from "node:crypto";
import type { refundStatus } from "@/db/schema";

export type RefundStatusValue = (typeof refundStatus.enumValues)[number];

export class RefundError extends Error {
  constructor(message: string, public readonly code: string) {
    super(message);
    this.name = "RefundError";
  }
}

/**
 * Create a local idempotency key for a refund request. Combines the payment
 * ID, amount, and a caller-supplied nonce. The nonce is generated by the
 * caller (e.g. the admin action or reconciliation routine) and is stable
 * across retries of the same refund — but does NOT depend on which admin
 * clicked. This means the same refund retried by a different admin produces
 * the same idempotency key.
 */
export function refundIdempotencyKey(input: {
  paymentId: string;
  amountPaise: number;
  nonce: string;
}): string {
  return createHash("sha256")
    .update(`${input.paymentId}:${input.amountPaise}:${input.nonce}`)
    .digest("hex");
}

/**
 * Create a provider idempotency key for Razorpay. Razorpay does not support
 * idempotency keys on refunds directly, but we store this key locally so the
 * reconciliation routine can detect duplicate provider calls. The key is
 * derived from the payment ID + amount + nonce, NOT from the admin user.
 */
export function providerRefundIdempotencyKey(input: {
  providerPaymentId: string;
  amountPaise: number;
  nonce: string;
}): string {
  return `refund:${input.providerPaymentId}:${input.amountPaise}:${input.nonce}`;
}

/**
 * Compute the total refund amount already recorded against a payment. Used to
 * prevent excess refunds.
 */
export async function getTotalRefundedForPayment(paymentId: string): Promise<number> {
  if (!isDatabaseConfigured()) return 0;
  const db = getDb();
  const rows = await db
    .select({ total: sum(refunds.amountPaise) })
    .from(refunds)
    .where(
      and(
        eq(refunds.paymentId, paymentId),
        sql`${refunds.status} IN ('pending', 'processing', 'processed')`,
      ),
    );
  const total = Number(rows[0]?.total ?? 0);
  return Number.isFinite(total) ? total : 0;
}

/**
 * Validate that a refund request is permissible:
 *  - Order must exist
 *  - Payment must be captured (or partially refunded)
 *  - Amount must be positive
 *  - Total refunds for this payment must not exceed captured amount
 */
export async function validateRefundRequest(input: {
  orderId: string;
  amountPaise: number;
  reason: string;
}): Promise<{ paymentId: string; providerPaymentId: string; capturedAmountPaise: number }> {
  if (!isDatabaseConfigured()) {
    throw new RefundError("Database is not configured", "db_unconfigured");
  }
  if (input.amountPaise <= 0) {
    throw new RefundError("Refund amount must be positive", "invalid_amount");
  }
  if (input.reason.trim().length === 0) {
    throw new RefundError("Refund reason is required", "missing_reason");
  }
  const db = getDb();
  const [payment] = await db
    .select()
    .from(payments)
    .where(eq(payments.orderId, input.orderId))
    .limit(1);
  if (!payment) {
    throw new RefundError("No payment record for this order", "no_payment");
  }
  if (payment.status !== "captured" && payment.status !== "refunded") {
    throw new RefundError(
      `Payment is in status ${payment.status}; only captured payments can be refunded`,
      "payment_not_captured",
    );
  }
  if (!payment.providerPaymentId) {
    throw new RefundError("Provider payment ID is missing", "no_provider_payment_id");
  }
  const alreadyRefunded = await getTotalRefundedForPayment(payment.id);
  const capturedAmount = payment.amountPaise;
  if (alreadyRefunded + input.amountPaise > capturedAmount) {
    throw new RefundError(
      `Refund total (${alreadyRefunded + input.amountPaise}) would exceed captured amount (${capturedAmount})`,
      "excess_refund",
    );
  }
  return {
    paymentId: payment.id,
    providerPaymentId: payment.providerPaymentId,
    capturedAmountPaise: capturedAmount,
  };
}

/**
 * Create a refund record atomically. Uses the `create_refund_atomic` PostgreSQL
 * function which locks the payment row, sums all existing refunds, validates
 * the amount, and inserts — all in a single transaction. Two concurrent refund
 * requests cannot both succeed if their combined total would exceed the
 * captured amount.
 *
 * The idempotency key is derived from the payment ID + amount + a nonce, NOT
 * from which admin clicked. The same refund retried by a different admin
 * produces the same key and is treated as a duplicate.
 *
 * If Razorpay is not configured, the refund is recorded with status `pending`
 * for manual processing. If the provider call fails, the refund is stored as
 * `failed` for admin retry — never silently rolled back.
 */
export async function createRefund(input: {
  orderId: string;
  amountPaise: number;
  reason: string;
  actorUserId: string;
  actorEmail?: string;
  /** Optional nonce for idempotency. If omitted, a random one is generated. */
  nonce?: string;
}): Promise<{ refundId: string; status: RefundStatusValue; idempotent: boolean }> {
  if (!isDatabaseConfigured()) {
    throw new RefundError("Database is not configured", "db_unconfigured");
  }
  if (input.amountPaise <= 0) {
    throw new RefundError("Refund amount must be positive", "invalid_amount");
  }
  if (input.reason.trim().length === 0) {
    throw new RefundError("Refund reason is required", "missing_reason");
  }

  const db = getDb();

  // First, load the payment to get the payment ID and provider payment ID.
  const [payment] = await db
    .select()
    .from(payments)
    .where(eq(payments.orderId, input.orderId))
    .limit(1);
  if (!payment) {
    throw new RefundError("No payment record for this order", "no_payment");
  }
  if (payment.status !== "captured" && payment.status !== "refunded") {
    throw new RefundError(
      `Payment is in status ${payment.status}; only captured payments can be refunded`,
      "payment_not_captured",
    );
  }

  const nonce = input.nonce ?? randomUUID();
  const idempotencyKey = refundIdempotencyKey({
    paymentId: payment.id,
    amountPaise: input.amountPaise,
    nonce,
  });

  // Call the atomic function — it locks the payment row, validates the amount,
  // and inserts the refund in a single transaction.
  let refundId: string;
  let refundStatus: string;
  let idempotent: boolean;

  try {
    const result = await db.execute(sql`
      SELECT * FROM create_refund_atomic(
        ${input.orderId}::uuid,
        ${payment.id}::uuid,
        ${input.amountPaise}::integer,
        ${input.reason}::text,
        ${input.actorUserId}::text,
        ${idempotencyKey}::text,
        ${providerRefundIdempotencyKey({
          providerPaymentId: payment.providerPaymentId ?? "",
          amountPaise: input.amountPaise,
          nonce,
        })}::text
      )
    `);
    const rows = Array.isArray(result) ? result : ((result as { rows?: Array<Record<string, unknown>> }).rows ?? []);
    const row = rows[0];
    if (!row) {
      throw new RefundError("Atomic refund insert returned no row", "insert_failed");
    }
    refundId = String(row.refund_id);
    refundStatus = String(row.refund_status);
    idempotent = Boolean(row.idempotent);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (message.includes("exceed captured amount")) {
      throw new RefundError(message, "excess_refund");
    }
    if (message.includes("only captured payments")) {
      throw new RefundError(message, "payment_not_captured");
    }
    throw new RefundError(message, "atomic_insert_failed");
  }

  // If idempotent (existing refund found), return it.
  if (idempotent) {
    const [existing] = await db
      .select({ status: refunds.status })
      .from(refunds)
      .where(eq(refunds.id, refundId))
      .limit(1);
    return {
      refundId,
      status: (existing?.status ?? "pending") as RefundStatusValue,
      idempotent: true,
    };
  }

  // If Razorpay is not configured, leave the refund in `pending` state.
  if (!isRazorpayConfigured() || !payment.providerPaymentId) {
    logger.warn(
      { event: "refund_pending_unconfigured", refundId, orderId: input.orderId },
      "Refund recorded but Razorpay is not configured — pending manual processing",
    );
    return { refundId, status: "pending" as RefundStatusValue, idempotent: false };
  }

  // Attempt to process via Razorpay immediately. Failures are stored as
  // `failed` for admin retry — never silently rolled back.
  try {
    await db
      .update(refunds)
      .set({ status: "processing", updatedAt: new Date() })
      .where(eq(refunds.id, refundId));
    const providerRefund = await getRazorpay().payments.refund(payment.providerPaymentId, {
      amount: input.amountPaise,
      notes: {
        reason: input.reason.slice(0, 200),
        actor: input.actorEmail ?? input.actorUserId,
      },
    });
    const providerStatus = String(providerRefund.status ?? "pending").toLowerCase();
    const finalStatus: RefundStatusValue =
      providerStatus === "processed" || providerStatus === "created"
        ? "processed"
        : providerStatus === "failed"
          ? "failed"
          : "processing";
    await db
      .update(refunds)
      .set({
        status: finalStatus,
        providerRefundId: String(providerRefund.id ?? null),
        providerResponse: providerRefund as unknown as Record<string, unknown>,
        processedAt: finalStatus === "processed" ? new Date() : null,
        updatedAt: new Date(),
      })
      .where(eq(refunds.id, refundId));
    return { refundId, status: finalStatus, idempotent: false };
  } catch (error) {
    const message = error instanceof Error ? error.message : "unknown_error";
    await db
      .update(refunds)
      .set({
        status: "failed",
        failureReason: message.slice(0, 500),
        updatedAt: new Date(),
      })
      .where(eq(refunds.id, refundId));
    logger.error(
      { event: "refund_failed", refundId, orderId: input.orderId, error: message },
      "Refund provider call failed",
    );
    return { refundId, status: "failed" as RefundStatusValue, idempotent: false };
  }
}

/**
 * Compute the aggregate refund status for an order. Updates the order's
 * `refundTotalPaise` field. Does NOT auto-transition order state — the admin
 * must explicitly mark the order as `refunded` after reviewing.
 */
export async function recomputeOrderRefundTotal(orderId: string): Promise<{
  refundTotalPaise: number;
  capturedAmountPaise: number;
  fullyRefunded: boolean;
}> {
  if (!isDatabaseConfigured()) {
    return { refundTotalPaise: 0, capturedAmountPaise: 0, fullyRefunded: false };
  }
  const db = getDb();
  const [payment] = await db
    .select()
    .from(payments)
    .where(eq(payments.orderId, orderId))
    .limit(1);
  if (!payment) return { refundTotalPaise: 0, capturedAmountPaise: 0, fullyRefunded: false };
  const totalRefunded = await getTotalRefundedForPayment(payment.id);
  await db
    .update(orders)
    .set({ refundTotalPaise: totalRefunded, updatedAt: new Date() })
    .where(eq(orders.id, orderId));
  return {
    refundTotalPaise: totalRefunded,
    capturedAmountPaise: payment.amountPaise,
    fullyRefunded: totalRefunded >= payment.amountPaise && payment.amountPaise > 0,
  };
}

/**
 * Process a refund webhook event from Razorpay. Updates the refund status
 * based on the provider's confirmation. This is the idempotent webhook-side
 * counterpart to {@link createRefund}.
 *
 * Supported events:
 *   - refund.processed: the refund succeeded at the provider. Mark the refund
 *     as `processed` and recompute the order's refund total.
 *   - refund.failed: the refund failed at the provider. Mark the refund as
 *     `failed` so the admin can retry.
 *   - refund.created: informational; mark as `processing` if currently pending.
 *
 * Idempotent: if the refund is already in the target state, this is a no-op.
 */
export async function processRefundWebhook(input: {
  eventType: string;
  providerPaymentId?: string;
  refundId?: string;
  eventId: string;
}): Promise<{ status: "completed" | "ignored" | "failed" | "retryable"; error?: string }> {
  if (!isDatabaseConfigured()) {
    return { status: "retryable", error: "Database not configured" };
  }
  if (!input.refundId) {
    return { status: "ignored" };
  }

  const db = getDb();

  // Find the refund by provider refund ID.
  const [refund] = await db
    .select()
    .from(refunds)
    .where(eq(refunds.providerRefundId, input.refundId))
    .limit(1);

  if (!refund) {
    // The refund wasn't created locally (maybe created directly in the
    // Razorpay dashboard). Log and ignore — an admin will need to reconcile.
    logger.warn(
      { event: "refund_webhook_no_local_refund", providerRefundId: input.refundId, eventId: input.eventId },
      "Refund webhook received for unknown local refund",
    );
    return { status: "ignored" };
  }

  switch (input.eventType) {
    case "refund.processed": {
      if (refund.status === "processed") return { status: "completed" };
      await db
        .update(refunds)
        .set({ status: "processed", processedAt: new Date(), updatedAt: new Date() })
        .where(eq(refunds.id, refund.id));
      await recomputeOrderRefundTotal(refund.orderId);
      logger.info(
        { event: "refund_processed", refundId: refund.id, providerRefundId: input.refundId },
        "Refund processed via webhook",
      );
      return { status: "completed" };
    }
    case "refund.failed": {
      if (refund.status === "failed") return { status: "completed" };
      await db
        .update(refunds)
        .set({ status: "failed", failureReason: "Provider reported refund failed", updatedAt: new Date() })
        .where(eq(refunds.id, refund.id));
      logger.warn(
        { event: "refund_failed", refundId: refund.id, providerRefundId: input.refundId },
        "Refund failed via webhook",
      );
      return { status: "completed" };
    }
    case "refund.created": {
      if (refund.status === "pending") {
        await db
          .update(refunds)
          .set({ status: "processing", updatedAt: new Date() })
          .where(eq(refunds.id, refund.id));
      }
      return { status: "completed" };
    }
    default:
      return { status: "ignored" };
  }
}

